// @generated by scripts/generateProtocolArtifacts.ts. DO NOT EDIT.

pub mod command_ids {
    pub const APP_FOCUS_WINDOW: &str = "app.focusWindow";
    pub const APP_LIST_WINDOWS: &str = "app.listWindows";
    pub const CONTROL_CANCEL: &str = "control.cancel";
    pub const ELEMENT_FIND: &str = "element.find";
    pub const ELEMENT_INVOKE: &str = "element.invoke";
    pub const ELEMENT_SET_VALUE: &str = "element.setValue";
    pub const HEALTH_GET_CAPABILITIES: &str = "health.getCapabilities";
    pub const HEALTH_PING: &str = "health.ping";
    pub const INPUT_CLICK: &str = "input.click";
    pub const INPUT_MOVE_MOUSE: &str = "input.moveMouse";
    pub const INPUT_TYPE_TEXT: &str = "input.typeText";
    pub const OBSERVABILITY_GET_METRICS: &str = "observability.getMetrics";
    pub const SCREEN_CAPTURE: &str = "screen.capture";

    pub const ALL: &[&str] = &[
        APP_FOCUS_WINDOW,
        APP_LIST_WINDOWS,
        CONTROL_CANCEL,
        ELEMENT_FIND,
        ELEMENT_INVOKE,
        ELEMENT_SET_VALUE,
        HEALTH_GET_CAPABILITIES,
        HEALTH_PING,
        INPUT_CLICK,
        INPUT_MOVE_MOUSE,
        INPUT_TYPE_TEXT,
        OBSERVABILITY_GET_METRICS,
        SCREEN_CAPTURE,
    ];
}

pub mod error_codes {
    pub const ADAPTER_FAILURE: &str = "ADAPTER_FAILURE";
    pub const AUTH_FAILED: &str = "AUTH_FAILED";
    pub const CANCELLED: &str = "CANCELLED";
    pub const INTERNAL: &str = "INTERNAL";
    pub const POLICY_DENIED: &str = "POLICY_DENIED";
    pub const TIMEOUT: &str = "TIMEOUT";
    pub const UNKNOWN_COMMAND: &str = "UNKNOWN_COMMAND";
    pub const UNSUPPORTED_VERSION: &str = "UNSUPPORTED_VERSION";
    pub const VALIDATION_FAILED: &str = "VALIDATION_FAILED";

    pub const ALL: &[&str] = &[
        ADAPTER_FAILURE,
        AUTH_FAILED,
        CANCELLED,
        INTERNAL,
        POLICY_DENIED,
        TIMEOUT,
        UNKNOWN_COMMAND,
        UNSUPPORTED_VERSION,
        VALIDATION_FAILED,
    ];
}
