import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { z } from "zod";
import { ErrorCodeSchema } from "../protocol/errors";
import { CommandPayloadSchema } from "../protocol/schema";
import { PROTOCOL_VERSION } from "../protocol/version";

export type SyncMode = "generate" | "check";

export interface ProtocolIdentifiersArtifact {
  protocolVersion: string;
  commandTypes: string[];
  errorCodes: string[];
}

export interface GeneratedArtifact {
  relativePath: string;
  content: string;
}

export interface SyncResult {
  mode: SyncMode;
  checked: string[];
  changed: string[];
}

export const PROTOCOL_JSON_ARTIFACT_PATH = path.join("protocol", "generated", "v1", "identifiers.json");
export const CSHARP_CONSTANTS_PATH = path.join(
  "client",
  "csharp",
  "Looksy.Client",
  "Generated",
  "ProtocolConstants.g.cs",
);
export const RUST_CONSTANTS_PATH = path.join("client", "rust", "src", "generated.rs");

export const GENERATED_ARTIFACT_PATHS = [
  PROTOCOL_JSON_ARTIFACT_PATH,
  CSHARP_CONSTANTS_PATH,
  RUST_CONSTANTS_PATH,
] as const;

function splitWords(value: string): string[] {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[^A-Za-z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter((part) => part.length > 0);
}

function toPascalCase(value: string): string {
  const words = splitWords(value);
  if (words.length === 0) {
    throw new Error(`Cannot derive PascalCase identifier from '${value}'.`);
  }

  return words.map((word) => `${word.charAt(0).toUpperCase()}${word.slice(1).toLowerCase()}`).join("");
}

function toUpperSnakeCase(value: string): string {
  const words = splitWords(value);
  if (words.length === 0) {
    throw new Error(`Cannot derive UPPER_SNAKE_CASE identifier from '${value}'.`);
  }

  return words.join("_").toUpperCase();
}

function sortedUnique(values: readonly string[], label: string): string[] {
  const deduped = new Set<string>();

  for (const value of values) {
    if (deduped.has(value)) {
      throw new Error(`Duplicate ${label} value detected: '${value}'.`);
    }

    deduped.add(value);
  }

  return [...deduped].sort((left, right) => {
    if (left < right) {
      return -1;
    }

    if (left > right) {
      return 1;
    }

    return 0;
  });
}

function extractCommandTypes(): string[] {
  const values: string[] = [];

  for (const option of CommandPayloadSchema.options) {
    if (!(option instanceof z.ZodObject)) {
      throw new Error("Expected command union option to be a ZodObject schema.");
    }

    const typeSchema = option.shape.type;
    if (!(typeSchema instanceof z.ZodLiteral) || typeof typeSchema.value !== "string") {
      throw new Error("Expected every command schema to provide a string literal 'type'.");
    }

    values.push(typeSchema.value);
  }

  return sortedUnique(values, "command type");
}

function extractErrorCodes(): string[] {
  return sortedUnique(ErrorCodeSchema.options, "error code");
}

export function getProtocolIdentifiersArtifact(): ProtocolIdentifiersArtifact {
  return {
    protocolVersion: PROTOCOL_VERSION,
    commandTypes: extractCommandTypes(),
    errorCodes: extractErrorCodes(),
  };
}

function renderJsonArtifact(artifact: ProtocolIdentifiersArtifact): string {
  return `${JSON.stringify(artifact, null, 2)}\n`;
}

function renderCSharpConstants(artifact: ProtocolIdentifiersArtifact): string {
  const commandLines = artifact.commandTypes.map((commandType) => {
    return `  public const string ${toPascalCase(commandType)} = \"${commandType}\";`;
  });

  const errorLines = artifact.errorCodes.map((errorCode) => {
    return `  public const string ${toPascalCase(errorCode)} = \"${errorCode}\";`;
  });

  const allCommandLines = artifact.commandTypes.map((commandType) => `    ${toPascalCase(commandType)},`);
  const allErrorLines = artifact.errorCodes.map((errorCode) => `    ${toPascalCase(errorCode)},`);

  return [
    "// <auto-generated />",
    "#nullable enable",
    "",
    "namespace Looksy.Client.Generated;",
    "",
    "public static class ProtocolCommandIds",
    "{",
    ...commandLines,
    "",
    "  public static readonly string[] All = new[]",
    "  {",
    ...allCommandLines,
    "  };",
    "}",
    "",
    "public static class ProtocolErrorCodes",
    "{",
    ...errorLines,
    "",
    "  public static readonly string[] All = new[]",
    "  {",
    ...allErrorLines,
    "  };",
    "}",
    "",
  ].join("\n");
}

function renderRustConstants(artifact: ProtocolIdentifiersArtifact): string {
  const commandLines = artifact.commandTypes.map((commandType) => {
    return `    pub const ${toUpperSnakeCase(commandType)}: &str = \"${commandType}\";`;
  });

  const errorLines = artifact.errorCodes.map((errorCode) => {
    return `    pub const ${toUpperSnakeCase(errorCode)}: &str = \"${errorCode}\";`;
  });

  const allCommandLines = artifact.commandTypes.map((commandType) => `        ${toUpperSnakeCase(commandType)},`);
  const allErrorLines = artifact.errorCodes.map((errorCode) => `        ${toUpperSnakeCase(errorCode)},`);

  return [
    "// @generated by scripts/generateProtocolArtifacts.ts. DO NOT EDIT.",
    "",
    "pub mod command_ids {",
    ...commandLines,
    "",
    "    pub const ALL: &[&str] = &[",
    ...allCommandLines,
    "    ];",
    "}",
    "",
    "pub mod error_codes {",
    ...errorLines,
    "",
    "    pub const ALL: &[&str] = &[",
    ...allErrorLines,
    "    ];",
    "}",
    "",
  ].join("\n");
}

export function buildGeneratedArtifacts(): GeneratedArtifact[] {
  const artifact = getProtocolIdentifiersArtifact();

  return [
    {
      relativePath: PROTOCOL_JSON_ARTIFACT_PATH,
      content: renderJsonArtifact(artifact),
    },
    {
      relativePath: CSHARP_CONSTANTS_PATH,
      content: renderCSharpConstants(artifact),
    },
    {
      relativePath: RUST_CONSTANTS_PATH,
      content: renderRustConstants(artifact),
    },
  ];
}

function readExistingContent(absPath: string): string | null {
  if (!existsSync(absPath)) {
    return null;
  }

  return readFileSync(absPath, "utf8");
}

function writeArtifact(rootDir: string, artifact: GeneratedArtifact): void {
  const absPath = path.join(rootDir, artifact.relativePath);
  mkdirSync(path.dirname(absPath), { recursive: true });
  writeFileSync(absPath, artifact.content, "utf8");
}

export function syncProtocolArtifacts(rootDir: string, mode: SyncMode): SyncResult {
  const artifacts = buildGeneratedArtifacts();
  const changed: string[] = [];

  for (const artifact of artifacts) {
    const absPath = path.join(rootDir, artifact.relativePath);
    const current = readExistingContent(absPath);

    if (current !== artifact.content) {
      changed.push(artifact.relativePath);

      if (mode === "generate") {
        writeArtifact(rootDir, artifact);
      }
    }
  }

  return {
    mode,
    checked: artifacts.map((artifact) => artifact.relativePath),
    changed,
  };
}

function runCli(): number {
  const mode: SyncMode = process.argv.includes("--check") ? "check" : "generate";
  const result = syncProtocolArtifacts(process.cwd(), mode);

  if (mode === "check") {
    if (result.changed.length > 0) {
      console.error("Protocol artifacts are out of date:");
      for (const relativePath of result.changed) {
        console.error(`- ${relativePath}`);
      }
      console.error("Run `npm run protocol:generate` to regenerate artifacts.");
      return 1;
    }

    console.log(`Protocol artifact check passed (${result.checked.length} files).`);
    return 0;
  }

  if (result.changed.length === 0) {
    console.log(`Protocol artifacts already up to date (${result.checked.length} files).`);
    return 0;
  }

  console.log(`Generated ${result.changed.length} protocol artifact(s):`);
  for (const relativePath of result.changed) {
    console.log(`- ${relativePath}`);
  }

  return 0;
}

if (require.main === module) {
  process.exitCode = runCli();
}
